Repository hapijs/wreck, pull requests merged in 2018-03, with the labels that each got.

#215 test(request) correct tests to check errors for boom instance
  CONTRIBUTING.md
  test/index.js
Labels: test

#216 add shortcut for HEAD
  lib/index.js
  test/index.js
Labels: enhancement

#217 Revert "add shortcut for HEAD"
  lib/index.js
  test/index.js
Labels: non-issue
